global class AcctInfoWrapper{
      public Boolean adultOHContentEnabled{get;set;}
      public Boolean adultAHContentEnabled{get;set;}
      public Boolean PediatricOHContentEnabled{get;set;}
      public Boolean PediatricAHContentEnabled{get;set;}
      public Boolean NLPEnabled{get;set;}
      public String acctId{get;set;}
      public String triageNowMode{get;set;}  //1. Trial   2.  Production
     }